# Generated by Django 3.2.9 on 2021-11-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='public_id',
            field=models.CharField(default='<function uuid4 at 0x7f4b6ef79a60>', max_length=32),
        ),
    ]
