# Generated by Django 3.2.9 on 2021-11-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='public_id',
            field=models.CharField(default='badae8e8-ef42-4717-a4fc-9ff9684f0910', max_length=32),
        ),
    ]
