# Generated by Django 3.2.9 on 2021-11-15 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('file_type', models.CharField(choices=[('f', 'File'), ('d', 'Directory')], max_length=1)),
                ('size', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to=files.models.user_directory_path, verbose_name='File')),
                ('access_link', models.CharField(default='<functio', max_length=8)),
                ('file_parent_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='files.filemodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
