# Generated by Django 3.2.9 on 2021-11-15 14:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileModel',
            new_name='UserFile',
        ),
    ]
